// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyHMP9ydxa_hHhFNj6HJE5tNoTDE93ESw',
    appId: '1:643376851:web:f056dcf70e626aaa321626',
    messagingSenderId: '643376851',
    projectId: 'chatapp-ff969',
    authDomain: 'chatapp-ff969.firebaseapp.com',
    storageBucket: 'chatapp-ff969.appspot.com',
    measurementId: 'G-SZY2L3B8FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8CvTUtc_3SITGfM2TrIziygSPqSf9MxQ',
    appId: '1:643376851:android:5d5ef2118862b868321626',
    messagingSenderId: '643376851',
    projectId: 'chatapp-ff969',
    storageBucket: 'chatapp-ff969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeDS8MqHuotKpHJh4Az9jVmceGvDg30o8',
    appId: '1:643376851:ios:dbc3eb4a1aebdb7f321626',
    messagingSenderId: '643376851',
    projectId: 'chatapp-ff969',
    storageBucket: 'chatapp-ff969.appspot.com',
    iosClientId: '643376851-ovt5ktoj977tdspu7m5pchf3k45cbiko.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
